ifndef MAKEFILE_DEFS
MAKEFILE_DEFS=1
# $(info MAKEFILE_DEFS=$(MAKEFILE_DEFS))

MAKEFLAGS += --no-builtin-rules
MAKEFLAGS += --no-builtin-variables
# MAKEFLAGS += --jobs=4
# test:
# 	@echo MAKEFLAGS=$(MAKEFLAGS)
# 	@echo MAKEOVERRIDES=$(MAKEOVERRIDES)

CC:=gcc
CFLAGS:=-std=gnu11 -g -O0 -Wall -Wextra -Wno-unused-parameter -Winline -D_GNU_SOURCE -pthread # -fmax-errors=1
%.o: %.c
	$(CC) -c $(CFLAGS) $(CFLAGS_EXTRA) -o $@ $<

else
$(error double inclusion)
endif
